import type { Codelist, DatasetInfo, EnergyCodelists, EnergyDictionary, Labels } from './types'

// Generated by `npm run eurostat:dictionary` into public/data/eurostat/energy/.
// Resolved when used (not at import), so Node scripts and tests can import this module.
const base = () => `${import.meta.env.BASE_URL}data/eurostat/energy/`

let dictionaryPromise: Promise<EnergyDictionary> | null = null
let codelistsPromise: Promise<EnergyCodelists> | null = null

async function getJson<T>(file: string): Promise<T> {
  const res = await fetch(base() + file)
  if (!res.ok) throw new Error(`Could not load ${file} (HTTP ${res.status})`)
  return res.json() as Promise<T>
}

/** Datasets, folder tree, dimensions and used codes for the Eurostat energy database. Cached. */
export function loadEnergyDictionary(): Promise<EnergyDictionary> {
  dictionaryPromise ??= getJson<EnergyDictionary>('dictionary.json').catch((err) => {
    dictionaryPromise = null
    throw err
  })
  return dictionaryPromise
}

/** Code labels (SIEC, NRG_BAL, GEO, UNIT…) in EN/DE/FR. Cached. */
export function loadEnergyCodelists(): Promise<EnergyCodelists> {
  codelistsPromise ??= getJson<EnergyCodelists>('codelists.json').catch((err) => {
    codelistsPromise = null
    throw err
  })
  return codelistsPromise
}

/** Picks the label in `lang`, falling back to English, then to `fallback`. */
export function pick(labels: Labels | undefined, lang: string, fallback = ''): string {
  return labels?.[lang as keyof Labels] ?? labels?.en ?? fallback
}

/** Label of one code, e.g. codeLabel(codelists, 'SIEC', 'C0000X0350-0370', 'de'). */
export function codeLabel(codelists: EnergyCodelists, codelist: string | null, code: string, lang: string): string {
  if (!codelist) return code
  return pick(codelists.codelists[codelist]?.codes[code], lang, code)
}

/** Codes of one dimension of a dataset with their labels. */
export function dimensionCodes(
  dataset: DatasetInfo,
  dimensionId: string,
  codelists: EnergyCodelists,
  lang: string,
): { code: string; label: string }[] {
  const dim = dataset.dimensions.find((d) => d.id === dimensionId)
  if (!dim) return []
  return dim.codes.map((code) => ({ code, label: codeLabel(codelists, dim.codelist, code, lang) }))
}

/** Folder path from the root to a dataset, e.g. Energy › Energy statistics - quantities › … */
export function datasetPath(dict: EnergyDictionary, code: string, lang: string): string[] {
  const path: string[] = []
  let folder: string | null = dict.datasets[code]?.folder ?? null
  while (folder) {
    const node: EnergyDictionary['folders'][string] | undefined = dict.folders[folder]
    if (!node) break
    path.unshift(pick(node.title, lang, folder))
    folder = node.parent
  }
  return path
}

const fold = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')

/**
 * Simple ranked search over dataset codes and titles (all languages) and, optionally,
 * the labels of the codes each dataset uses (e.g. "hydrogen", "Erdgas", "BE").
 */
export function searchDatasets(
  dict: EnergyDictionary,
  query: string,
  { codelists, limit = 20 }: { codelists?: EnergyCodelists; limit?: number } = {},
): DatasetInfo[] {
  const terms = fold(query).split(/\s+/).filter(Boolean)
  if (!terms.length) return []

  const scored = Object.values(dict.datasets).map((ds) => {
    const titles = fold(Object.values(ds.title).join(' '))
    let score = 0
    for (const t of terms) {
      if (ds.code.toLowerCase() === t) score += 10
      else if (ds.code.toLowerCase().includes(t)) score += 4
      if (titles.includes(t)) score += 3
      if (codelists && score === 0) {
        const hit = ds.dimensions.some((dim) =>
          dim.codes.some((code) => {
            const labels = dim.codelist ? codelists.codelists[dim.codelist]?.codes[code] : undefined
            return code.toLowerCase() === t || Object.values(labels ?? {}).some((l) => fold(l).includes(t))
          }),
        )
        if (hit) score += 1
      }
    }
    return { ds, score }
  })

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score || a.ds.code.localeCompare(b.ds.code))
    .slice(0, limit)
    .map((s) => s.ds)
}

const FREQ_NAMES: Record<string, string> = { A: 'annual', S: 'half-yearly', Q: 'quarterly', M: 'monthly', D: 'daily' }

/**
 * Compact plain-text description of a dataset for the language model: what it contains,
 * which dimensions and units exist and which selection is recommended. The model is told to
 * use only these units and codes, so it picks from the dictionary instead of inventing.
 */
export function describeDataset(
  dict: EnergyDictionary,
  codelists: EnergyCodelists | null,
  code: string,
  lang = 'en',
  /** Example codes per dimension. Off for small models: they tend to describe the examples instead. */
  { examples = true }: { examples?: boolean } = {},
): string {
  const ds = dict.datasets[code]
  if (!ds) return ''
  const freq = ds.defaults.freq ? FREQ_NAMES[ds.defaults.freq] ?? ds.defaults.freq : ''
  const unitText = (u: string) => {
    const info = dict.units[u]
    return info ? `${u} (${info.symbol}, ${pick(info.label, lang, u)})` : u
  }
  const dims = ds.dimensions
    .filter((d) => !['freq', 'unit'].includes(d.id))
    .map((d) => {
      const name = pick(dict.dimensions[d.concept.toLowerCase()] ?? dict.dimensions[d.id], lang, d.id)
      if (!examples) return `${d.id} (${name}, ${d.codes.length} codes)`
      const sample = d.codes
        .slice(0, 4)
        .map((c) => {
          // Keep examples short: the model's context window is small.
          const label = codelists ? codeLabel(codelists, d.codelist, c, lang) : c
          return `${c}=${label.length > 48 ? `${label.slice(0, 45)}…` : label}`
        })
        .join('; ')
      return `${d.id} (${name}, ${d.codes.length} codes, e.g. ${sample})`
    })

  const lines = [
    `Dataset ${ds.code}: "${pick(ds.title, lang, ds.code)}"${freq ? `, ${freq}` : ''}, ${ds.dataStart ?? '?'}–${ds.dataEnd ?? '?'}, last update ${ds.lastUpdate ?? 'n/a'}.`,
    `Dimensions: ${dims.join(' | ') || 'none'}.`,
  ]
  if (ds.units.length) {
    const kind = ds.multipleUnits
      ? ds.unitsAreAlternatives
        ? 'several units for the same measure — choose one'
        : 'units measure different things — use the one that matches the question'
      : 'single unit'
    lines.push(`Units (${kind}): ${ds.units.map(unitText).join(', ')}. Default: ${ds.defaults.unit ?? ds.units[0]}.`)
  }
  const other = Object.entries(ds.defaults).filter(([k]) => !['unit', 'freq'].includes(k))
  if (other.length) lines.push(`Recommended selection: ${other.map(([k, v]) => `${k}=${v}`).join(', ')}.`)
  return lines.join('\n')
}

export type { Codelist, DatasetInfo, EnergyCodelists, EnergyDictionary, Labels }
