import type { Strings } from '../i18n'
import type { DashStrings } from './execute'

/** The dashboard builder's strings, from the UI strings of one language (app, scripts, tests). */
export function dashStrings(t: Strings): DashStrings {
  return {
    latest: t.dLatest,
    highest: t.dHighest,
    lowest: t.dLowest,
    total: t.dTotal,
    vs: t.dVs,
    dataTable: t.dDataTable,
    summaryLatest: t.dSummaryLatest,
    summaryChange: t.dSummaryChange,
    summaryRange: t.dSummaryRange,
    summaryCompare: t.dSummaryCompare,
    summaryMix: t.dSummaryMix,
    noData: t.dNoData,
    noteNoMonthly: t.dNoteNoMonthly,
    noteAssumedHouseholds: t.dNoteAssumedHouseholds,
    noteAssumedEu: t.dNoteAssumedEu,
    sugAllCountries: t.dSugAllCountries,
    sugWithEu: t.dSugWithEu,
    sugHistory: t.dSugHistory,
    sugMonthly: t.dSugMonthly,
    sugMix: t.dSugMix,
    sugExplain: t.dSugExplain,
    sugUnit: t.dSugUnit,
    noteCached: t.dNoteCached,
    evolution: t.dEvolution,
    rankingIn: t.dRankingIn,
    changeVs: t.dChangeVs,
    changeSince: t.dChangeSince,
    shareOfTotal: t.dShareOfTotal,
    yearOnYear: t.dYearOnYear,
    yearEarlier: t.dYearEarlier,
    monthByYear: t.dMonthByYear,
    average: t.dAverage,
    selectionAverage: t.dSelectionAverage,
    sharesOverTime: t.dSharesOverTime,
    mixRanking: t.dMixRanking,
    heatmapTitle: t.dHeatmapTitle,
    yearsShort: t.dYearsShort,
    monthsShort: t.dMonthsShort,
    allYears: t.dAllYears,
    noteTop: t.dNoteTop,
    noteBottom: t.dNoteBottom,
    insights: t.dInsights,
    companions: t.dCompanions,
    answer: t.dAnswer,
  }
}
